/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        outline: "#99907c",
        "on-tertiary-fixed": "#1c1b1b",
        "on-background": "#e5e2e1",
        error: "#ffb4ab",
        "on-primary-container": "#554300",
        "on-primary-fixed-variant": "#574500",
        "on-primary": "#3c2f00",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#474646",
        "surface-container": "#201f1f",
        "primary-fixed-dim": "#e9c349",
        "tertiary-fixed": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c9c6c5",
        "secondary-fixed-dim": "#c9c6c1",
        "surface-container-low": "#1c1b1b",
        "on-secondary": "#31312d",
        "primary-fixed": "#ffe088",
        "on-secondary-container": "#b7b5af",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "error-container": "#93000a",
        "on-tertiary": "#313030",
        "on-primary-fixed": "#241a00",
        primary: "#f2ca50",
        "tertiary-container": "#b5b2b2",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2dc",
        "on-surface-variant": "#d0c5af",
        "on-surface": "#e5e2e1",
        "primary-container": "#d4af37",
        "outline-variant": "#4d4635",
        tertiary: "#d0cecd",
        "surface-variant": "#353534",
        "on-tertiary-container": "#464545",
        "on-secondary-fixed": "#1c1c18",
        "on-secondary-fixed-variant": "#474743",
        "surface-bright": "#393939",
        surface: "#131313",
        secondary: "#c9c6c1",
        "secondary-container": "#474743",
        "inverse-primary": "#735c00",
        "on-error": "#690005",
        "surface-tint": "#e9c349"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "var(--gutter)",
        "section-gap": "var(--section-gap)",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "margin-mobile": "24px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        quote: ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Playfair Display"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Playfair Display"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        quote: ["24px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
